[package]
name = "testutil"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoincore-rpc = "0.18.0"
testcontainers = "0.15.0"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
env_logger = "*"
